# -*- coding: utf-8 -*-

if __name__ == "__main__":
	print "Sorry, you can't run this stand-alone."
	exit()

VERSION = '0.1'

FLOOR_HEIGHT = 40
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600
GAME_HEIGHT = 110 * FLOOR_HEIGHT
GAME_WIDTH = 75 * FLOOR_HEIGHT
GAME_RATIO = GAME_HEIGHT / GAME_WIDTH
BOTTOM = GAME_HEIGHT - WINDOW_HEIGHT
CENTER = ( GAME_WIDTH - WINDOW_WIDTH ) / 2
MINI_WIDTH = GAME_WIDTH / FLOOR_HEIGHT
MINI_HEIGHT = GAME_HEIGHT / FLOOR_HEIGHT
MINI_RATIO = FLOOR_HEIGHT